#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         0.5
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a 'jetbrains-goland' state=floating follow=on desktop="^1"
bspc rule -a falkon desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^3'
bspc rule -a brave-browser desktop='^3'
bspc rule -a dolphin desktop='^4'
bspc rule -a vlc desktop='^6'


$HOME/.config/polybar/launch.sh --panels &

~/.fehbg
redshift -x 
redshift -O 4000 &

set -U SXHKD_SHELL /usr/bin/bash &

export QT_QPA_PLATFORMTHEME=qt5ct &

kill picom
picom -b --experimental-backends -f

dunst &

setxkbmap -layout "us,ir" -option "grp:alt_shift_toggle" &

xsetroot -cursor_name left_ptr

wmname LG3D

