#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         0.5
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a 'jetbrains-pycharm' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^3'
bspc rule -a dolphin desktop='^4'
bspc rule -a vlc desktop='^6'


$HOME/.config/polybar/launch.sh --panels &

#feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &

# feh --bg-scale $HOME/Downloads/leaves_line_neon_139772_3840x2400.jpg
feh --bg-scale $HOME/Downloads/Telegram\ Desktop/884853.jpg

redshift -x 
redshift -O 4500 &

set -U SXHKD_SHELL /usr/bin/bash &

export QT_QPA_PLATFORMTHEME=qt5ct &

picom -b -f

setxkbmap -layout "us,ir" -option "grp:alt_shift_toggle" &

xsetroot -cursor_name left_ptr

wmname LG3D

